import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Card, Tag, Typography, List, Input, Button, message, Space, Switch, Popconfirm } from 'antd';
import MarkdownPreview from '@uiw/react-markdown-preview';
import '@uiw/react-markdown-preview/markdown.css';
import api from '../utils/api';
import useAuthStore from '../stores/auth';

function ArticleDetailPage() {
  const { id } = useParams();
  const [article, setArticle] = useState<any>(null);
  const [comments, setComments] = useState<any[]>([]);
  const [comment, setComment] = useState('');
  const { user } = useAuthStore();
  const navigate = useNavigate();

  useEffect(() => {
    const load = async () => {
      const { data } = await api.get(`/articles/${id}`);
      setArticle(data);
      const c = await api.get(`/articles/${id}/comments`);
      setComments(c.data);
    };
    load();
  }, [id]);

  const submitComment = async () => {
    if (!comment) return;
    try {
      const { data } = await api.post(`/articles/${id}/comments`, { content: comment });
      setComments((prev) => [...prev, data]);
      setComment('');
    } catch (err: any) {
      message.error(err.response?.data?.detail || '评论失败');
    }
  };

  const like = async () => {
    try {
      await api.post(`/articles/${id}/like`);
      message.success('已点赞');
    } catch (err: any) {
      message.error(err.response?.data?.detail || '点赞失败');
    }
  };

  const togglePublish = async (checked: boolean) => {
    try {
      await api.patch(`/articles/${id}`, { is_published: checked });
      setArticle((prev: any) => ({ ...prev, is_published: checked }));
      message.success(checked ? '已发布到社区' : '已设为私有');
    } catch (err: any) {
      message.error(err.response?.data?.detail || '更新失败');
    }
  };

  const deleteArticle = async () => {
    try {
      await api.patch(`/articles/${id}`, { delete: true });
      message.success('已删除');
      navigate(-1);
    } catch (err: any) {
      if (err.response?.status === 401) {
        message.error('登录过期，请先登录');
        navigate('/login');
      } else {
        message.error(err.response?.data?.detail || '删除失败');
      }
    }
  };

  const goBack = () => navigate(-1);

  if (!article) return null;

  const canEdit = user && user.id === article.author_id;
  const isAutoGenerated = !!article.is_auto_generated;

  return (
    <Space direction="vertical" style={{ width: '100%' }} size="large">
      <Card
        title={article.title}
        extra={
          <Space>
            {canEdit && (
              <Space size={8}>
                <Typography.Text>发布到社区</Typography.Text>
                <Switch checked={article.is_published} onChange={togglePublish} />
              </Space>
            )}
            {canEdit && !isAutoGenerated && (
              <Button onClick={() => navigate(`/articles/new?edit_id=${article.id}`)}>编辑</Button>
            )}
            {canEdit && (
              <Popconfirm title="确定删除这篇文章吗？" onConfirm={deleteArticle} okText="删除" cancelText="取消">
                <Button danger>删除</Button>
              </Popconfirm>
            )}
            <Button onClick={like}>点赞</Button>
            <Button onClick={goBack}>返回</Button>
          </Space>
        }
      >
        <Space style={{ marginBottom: 12 }}>
          {article.tags.map((t: string) => <Tag key={t}>{t}</Tag>)}
          <Typography.Text type="secondary">{new Date(article.created_at).toLocaleString()}</Typography.Text>
        </Space>
        <div data-color-mode="light">
          <MarkdownPreview source={article.content_markdown || ''} />
        </div>
      </Card>

      <Card title="评论">
        <List
          dataSource={comments}
          renderItem={(c) => (
            <List.Item>
              <List.Item.Meta
                title={`用户 ${c.user_id}`}
                description={<Typography.Text>{c.content}</Typography.Text>}
              />
              <Typography.Text type="secondary">{new Date(c.created_at).toLocaleString()}</Typography.Text>
            </List.Item>
          )}
        />
        {user && (
          <Space style={{ marginTop: 12 }}>
            <Input.TextArea rows={2} value={comment} onChange={(e) => setComment(e.target.value)} placeholder="写下你的想法" />
            <Button type="primary" onClick={submitComment}>发布评论</Button>
          </Space>
        )}
      </Card>
    </Space>
  );
}

export default ArticleDetailPage;
